### ISSUE TITLE
Error: could not load cache

### ISSUE THREAD

**Issue by francescor** [filippofinke/cli-gpt#1]
```
…/cli-gpt# cmake --build . --target install
Error: could not load cache


# cmake --version
cmake version 3.26.0

# cat /etc/os-release 
NAME="Fedora Linux"
VERSION="37 (Workstation Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Workstation Edition)"
...


# which curl 
/usr/bin/curl

# curl --version
curl 7.85.0 (x86_64-redhat-linux-gnu) libcurl/7.85.0 OpenSSL/3.0.8 zlib/1.2.12 libidn2/2.3.4 nghttp2/1.51.0
Release-Date: 2022-08-31


```

**Comment by filippofinke** [comment]
Hello, try to run `cmake .` and then `cmake --build . --target install`

**Comment by francescor** [comment]
```
 cmake .
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CURL (missing: CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindCURL.cmake:182 (find_package_handle_standard_args)
  CMakeLists.txt:10 (find_package)
```

Fixed by commenting out `include_directories(/usr/local/opt/curl/include/` in CMakeLists.txt and installing

```
sudo yum install libcurl-devel
```

then 

```
sudo cmake --build . --target install
```

**Comment by francescor** [comment]
if this can help

 ```
sudo repoquery -l libcurl-devel | egrep -v "man|doc"

/usr/bin/curl-config
/usr/include/curl
/usr/include/curl/curl.h
/usr/include/curl/curlver.h
/usr/include/curl/easy.h
/usr/include/curl/header.h
/usr/include/curl/mprintf.h
/usr/include/curl/multi.h
/usr/include/curl/options.h
/usr/include/curl/stdcheaders.h
/usr/include/curl/system.h
/usr/include/curl/typecheck-gcc.h
/usr/include/curl/urlapi.h
/usr/lib/libcurl.so
/usr/lib/pkgconfig/libcurl.pc
/usr/share/aclocal/libcurl.m4
/usr/bin/curl-config
/usr/include/curl
/usr/include/curl/curl.h
/usr/include/curl/curlver.h
/usr/include/curl/easy.h
/usr/include/curl/header.h
/usr/include/curl/mprintf.h
/usr/include/curl/multi.h
/usr/include/curl/options.h
/usr/include/curl/stdcheaders.h
/usr/include/curl/system.h
/usr/include/curl/typecheck-gcc.h
/usr/include/curl/urlapi.h
/usr/lib64/libcurl.so
/usr/lib64/pkgconfig/libcurl.pc
/usr/share/aclocal/libcurl.m4
```

**Comment by filippofinke** [comment]
Updated the CMakeLists.txt https://github.com/filippofinke/cli-gpt/commit/49467816141ecc69ed68943215d5f88f8dc68730

Working on
```
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Comment by pzim-devdata** [comment]
I have this error message : 

`sudo apt update && sudo apt upgrade && sudo apt install curl && sudo apt-get install libcurl4-openssl-dev libssl-dev`

`cmake .`

-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.88.1")  
-- Configuring done
-- Generating done
-- Build files have been written to: $HOME/Bureau/cli-gpt-main


`cmake --build . --target install`

[ 50%] Building CXX object CMakeFiles/cli-gpt.dir/main.cpp.o
**$HOME/Bureau/cli-gpt-main/main.cpp:2:10: fatal error: openai.hpp: Aucun fichier ou dossier de ce type
    2 | #include "openai.hpp"
      |          ^~~~~~~~~~~~
compilation terminated.**
gmake[2]: *** [CMakeFiles/cli-gpt.dir/build.make:76 : CMakeFiles/cli-gpt.dir/main.cpp.o] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:83 : CMakeFiles/cli-gpt.dir/all] Erreur 2
gmake: *** [Makefile:136 : all] Erreur 2

**Comment by filippofinke** [comment]
Did you clone the repository with git clone --recurse-submodules https://github.com/filippofinke/cli-gpt ?

**Comment by pzim-devdata** [comment]
> Did you clone the repository with git clone --recurse-submodules https://github.com/filippofinke/cli-gpt ?

Yes, it was this, thanks !!!

So this is how I should install it : 
1. Install dependencies : 
 `sudo apt update && sudo apt upgrade && sudo apt install curl && sudo apt-get install libcurl4-openssl-dev libssl-dev`
2. Clone the project :  
`git clone --recurse-submodules https://github.com/filippofinke/cli-gpt`
3. go to the folder : 
`cd cli-gpt`
4. Install with cmake : 
`cmake .`
then
`sudo cmake --build . --target install`
5. configure : 
`export OPENAI_API_KEY=<your openai api key>`
6. And it's perfectly working : 
`cli-gpt post on github a message to say thank you to filippofinke at this address :
https://github.com/filippofinke/cli-gpt/issues/1`
