### ISSUE TITLE
Instructions for installing on Windows?

### ISSUE THREAD

**Issue by chaoscreater** [filippofinke/cli-gpt#3]
Hi there, could you please provide a more detailed install instruction for Windows?

- I have CMake installed.
- I've cloned your repo.
- I've CD into the folder and ran cmake and got a "could not load cache" error.

![image](https://user-images.githubusercontent.com/18227319/228124985-254d53d1-8215-4378-a31b-16b1c1d0127e.png)

**Comment by filippofinke** [comment]
See https://github.com/filippofinke/cli-gpt/issues/1

**Comment by chaoscreater** [comment]
Uhh yeah that's for Linux, so the instructions isn't exactly for Windows....



After running `cmake .`, I got this error:

![image](https://user-images.githubusercontent.com/18227319/229032052-03ceb5aa-d903-42f8-9d59-df462f7581bd.png)

Then after Googling a bit, I installed **mingw32** on Windows, which is like a C++ compiler or something. Here're the link:
https://www.mingw-w64.org/downloads/

From the link above, I chose this and downloaded the file:
https://github.com/niXman/mingw-builds-binaries/releases

I unzipped it to here:
C:\mingw32\

Then I added this to my PATH environment variable:
**C:\mingw32\bin**

Next, I downloaded cURL from here:
https://curl.se/windows/

I unzipped it to here:
C:\curl-8.0.1_5-win32-mingw

Then added the following to my PATH:
**C:\curl-8.0.1_5-win32-mingw\bin
C:\curl-8.0.1_5-win32-mingw\lib**

I then tested `cmake .` again and got the same error.

I then deleted the file `CMakeCache.txt` from the cli-gpt folder and then ran this:

`cmake -G "MinGW Makefiles"`

And now I got this:

![image](https://user-images.githubusercontent.com/18227319/229041304-142459e8-abaa-494c-bac9-ac2897189311.png)



Then, I ran `cmake --build . --target install` and I'm getting this new error:

![image](https://user-images.githubusercontent.com/18227319/229041709-2a93cc8f-b8d5-468f-8810-bbf3027e7f2a.png)

I then tried just `cmake --build .` and was able to build an exe, but I can't seem to install it:

![image](https://user-images.githubusercontent.com/18227319/229042415-66385934-0871-4515-8b13-8feb39d51548.png)

I have no idea what I'm doing. I'm not a programmer and I don't know anything about CMAKE or any of this stuff. Would appreciate it if you can provide a bit more help.

**Comment by chaoscreater** [comment]
I think I know what the issue is.

It's talking about "no rule to make target 'install'" and from what I'm reading in the StackOverFlow link below, it seems you need to define a "install" rule in the CMakeLists.txt file?

https://stackoverflow.com/questions/48428647/how-to-use-cmake-to-install

The problem is, I'm using Windows. There isn't a rule for Windows in the file it seems. Does your tool actually work on Windows? I tried to run the cli-gpt exe that was compiled (see my screenshot from the previous post) and it didn't do anything.

```
if(APPLE)
    install(TARGETS cli-gpt DESTINATION /usr/local/bin)
elseif(UNIX)
    install(TARGETS cli-gpt DESTINATION /usr/bin/)
endif()
```
